/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trackmylove;

/**
 *
 * @author Lance
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());
    private tml_model.Member loggedMember;
    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame(tml_model.Member member) {
        this.loggedMember = member;
        initComponents();
        setLocationRelativeTo(null);
    lblWelcome.setText(member.getFullName());
    lblRole.setText(member.getRole().toUpperCase());
    lblHousehold.setText("Household #" + member.getHouseholdId());
    loadRecentLogs();
    }
    private void loadRecentLogs() {
    tml_dao.MedicationLogDAO logDAO = new tml_dao.MedicationLogDAO();
    java.util.List<tml_model.MedicationLog> logs = logDAO.findAll(loggedMember.getHouseholdId());
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("Log ID");
    model.addColumn("Patient");
    model.addColumn("Given By");
    model.addColumn("Date");
    model.addColumn("Notes");
    for (tml_model.MedicationLog log : logs) {
        model.addRow(new Object[]{
            "#" + log.getId(),
            log.getPatientName(),
            log.getGivenByName(),
            log.getLogDate(),
            log.getNotes()
        });
    }
    tblLogs.setModel(model);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnMembers = new javax.swing.JButton();
        pnlAvatar = new javax.swing.JPanel();
        lblInitials = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHousehold = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnMedications = new javax.swing.JButton();
        btnGiveMeds = new javax.swing.JButton();
        btnAllLogs = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        lblDashTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlLogsCard = new javax.swing.JPanel();
        lblLogsTitle = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard — TrackMyLove");
        setSize(new java.awt.Dimension(900, 600));

        pnlSidebar.setBackground(new java.awt.Color(8, 80, 65));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(170, 600));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(225, 245, 238));
        lblWelcome.setText("Welcome!");

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblRole.setForeground(new java.awt.Color(93, 202, 165));
        lblRole.setText("CAREGIVER");

        btnMembers.setBackground(new java.awt.Color(8, 80, 65));
        btnMembers.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnMembers.setForeground(new java.awt.Color(159, 225, 203));
        btnMembers.setText("Members");
        btnMembers.setBorderPainted(false);
        btnMembers.addActionListener(this::btnMembersActionPerformed);

        pnlAvatar.setBackground(new java.awt.Color(29, 158, 117));

        lblInitials.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblInitials.setForeground(new java.awt.Color(225, 245, 238));
        lblInitials.setText("LB");

        javax.swing.GroupLayout pnlAvatarLayout = new javax.swing.GroupLayout(pnlAvatar);
        pnlAvatar.setLayout(pnlAvatarLayout);
        pnlAvatarLayout.setHorizontalGroup(
            pnlAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvatarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInitials, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAvatarLayout.setVerticalGroup(
            pnlAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAvatarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInitials)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(225, 245, 238));
        jLabel1.setText("Lance Bimbo");

        lblHousehold.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        lblHousehold.setForeground(new java.awt.Color(93, 202, 165));
        lblHousehold.setText("Household #1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 202, 165));
        jLabel2.setText("NAVIGATION");

        btnDashboard.setBackground(new java.awt.Color(29, 158, 117));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(225, 245, 238));
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorderPainted(false);
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        btnMedications.setBackground(new java.awt.Color(8, 80, 65));
        btnMedications.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnMedications.setForeground(new java.awt.Color(159, 225, 203));
        btnMedications.setText("Medications");
        btnMedications.setBorderPainted(false);
        btnMedications.addActionListener(this::btnMedicationsActionPerformed);

        btnGiveMeds.setBackground(new java.awt.Color(8, 80, 65));
        btnGiveMeds.setForeground(new java.awt.Color(159, 225, 203));
        btnGiveMeds.setText("Give Meds");
        btnGiveMeds.setBorderPainted(false);
        btnGiveMeds.addActionListener(this::btnGiveMedsActionPerformed);

        btnAllLogs.setBackground(new java.awt.Color(8, 80, 65));
        btnAllLogs.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnAllLogs.setForeground(new java.awt.Color(159, 225, 203));
        btnAllLogs.setText("All Logs");
        btnAllLogs.setBorderPainted(false);
        btnAllLogs.addActionListener(this::btnAllLogsActionPerformed);

        btnLogout.setBackground(new java.awt.Color(192, 57, 43));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSidebarLayout.createSequentialGroup()
                        .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAllLogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGiveMeds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMedications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMembers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHousehold)
                            .addComponent(jLabel1)
                            .addComponent(lblRole))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSidebarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRole)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHousehold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMembers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedications)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGiveMeds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAllLogs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(22, 22, 22))
        );

        pnlMain.setBackground(new java.awt.Color(241, 239, 232));

        lblDashTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDashTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblDashTitle.setText("Dashboard");

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblSubtitle.setForeground(java.awt.Color.gray);
        lblSubtitle.setText("Santos Family · June 1, 2025");

        pnlLogsCard.setBackground(new java.awt.Color(255, 255, 255));

        lblLogsTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblLogsTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblLogsTitle.setText("Recent medication logs");

        btnRefresh.setBackground(new java.awt.Color(225, 245, 238));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(8, 80, 65));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        tblLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLogs);

        javax.swing.GroupLayout pnlLogsCardLayout = new javax.swing.GroupLayout(pnlLogsCard);
        pnlLogsCard.setLayout(pnlLogsCardLayout);
        pnlLogsCardLayout.setHorizontalGroup(
            pnlLogsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogsCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogsCardLayout.createSequentialGroup()
                        .addComponent(lblLogsTitle)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogsCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlLogsCardLayout.setVerticalGroup(
            pnlLogsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogsCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogsTitle)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlLogsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDashTitle)
                    .addComponent(lblSubtitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLogsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembersActionPerformed
    new trackmylove.MembersFrame(loggedMember).setVisible(true);
    }//GEN-LAST:event_btnMembersActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    loadRecentLogs();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
    loadRecentLogs();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnMedicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicationsActionPerformed
    new trackmylove.MedicationsFrame(loggedMember).setVisible(true);
    }//GEN-LAST:event_btnMedicationsActionPerformed

    private void btnGiveMedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiveMedsActionPerformed
    new trackmylove.LogFrame(loggedMember).setVisible(true);
    }//GEN-LAST:event_btnGiveMedsActionPerformed

    private void btnAllLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllLogsActionPerformed
    loadRecentLogs();
    }//GEN-LAST:event_btnAllLogsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
    this.dispose();
    new trackmylove.Loginframe().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllLogs;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnGiveMeds;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMedications;
    private javax.swing.JButton btnMembers;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblDashTitle;
    private javax.swing.JLabel lblHousehold;
    private javax.swing.JLabel lblInitials;
    private javax.swing.JLabel lblLogsTitle;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlAvatar;
    private javax.swing.JPanel pnlLogsCard;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JTable tblLogs;
    // End of variables declaration//GEN-END:variables
}
