/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trackmylove;

/**
 *
 * @author Lance
 */
public class LogDetailsFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogDetailsFrame.class.getName());

    private tml_model.Member loggedMember;
    private int currentLogId;

    public LogDetailsFrame(tml_model.Member member, int logId) {
    this.loggedMember = member;
    this.currentLogId = logId;
    initComponents();
    setLocationRelativeTo(null);
    lblLogInfo.setText("Log #" + logId);
    loadMedications();
    loadDetails();
}

private void loadMedications() {
    tml_dao.MedicationDAO dao = new tml_dao.MedicationDAO();
    java.util.List<tml_model.Medication> list = dao.findAll();
    cmbMedication.removeAllItems();
    for (tml_model.Medication m : list) {
        cmbMedication.addItem(m.getName() + " " + m.getDosage() + m.getUnit() + " id:" + m.getId());
    }
}

private void loadDetails() {
    tml_dao.LogDetailDAO dao = new tml_dao.LogDetailDAO();
    java.util.List<tml_model.LogDetail> list = dao.findByLog(currentLogId);
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Medication");
    model.addColumn("Time Given");
    model.addColumn("Status");
    model.addColumn("Side Effects");
    for (tml_model.LogDetail d : list) {
        model.addRow(new Object[]{
            d.getId(),
            d.getMedicationName(),
            d.getTimeGiven(),
            d.isWasTaken() ? "Taken" : "Skipped",
            d.getSideEffects()
        });
    }
    jTable1.setModel(model);
}

private void clearForm() {
    cmbMedication.setSelectedIndex(0);
    txtTime.setText("");
    cmbWasTaken.setSelectedIndex(0);
    txtSideEffects.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblLogInfo = new javax.swing.JLabel();
        medication = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbMedication = new javax.swing.JComboBox<>();
        txtTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbWasTaken = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSideEffects = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        tblDetails = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblTitle.setText("Log Details");

        lblLogInfo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblLogInfo.setForeground(java.awt.Color.gray);
        lblLogInfo.setText("Log #");

        medication.setText("Medication");

        jLabel2.setText("Time Given * (HH:MM)");

        jLabel3.setText("Was it taken?");

        cmbWasTaken.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmbWasTaken.addActionListener(this::cmbWasTakenActionPerformed);

        jLabel4.setText("Side Effects");

        btnAdd.setBackground(new java.awt.Color(29, 158, 117));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add to Log");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setBackground(new java.awt.Color(192, 57, 43));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnBack.setText("Back to Dashboard");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetails.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medication)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbMedication, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cmbWasTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTitle)
                                            .addComponent(lblLogInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAdd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDelete))))
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(txtSideEffects, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(tblDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medication)
                            .addComponent(cmbMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(cmbWasTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSideEffects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnDelete)))
                    .addComponent(tblDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(btnBack)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbWasTakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbWasTakenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbWasTakenActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

if (cmbMedication.getSelectedItem() == null) {
    tml_dao.InputValidator.showError(this, "Please select a medication.");
    return;
}
if (!tml_dao.InputValidator.isValidTime(txtTime.getText().trim())) {
    tml_dao.InputValidator.showError(this, "Time must be in HH:MM format.");
    return;
}

tml_model.Medication med = (tml_model.Medication) cmbMedication.getSelectedItem();
tml_dao.LogDetailDAO dao = new tml_dao.LogDetailDAO();

if (dao.alreadyLogged(currentLogId, med.getId())) {
    tml_dao.InputValidator.showError(this, "That medication is already in this log.");
    return;
}

tml_model.LogDetail detail = new tml_model.LogDetail();
detail.setLogId(currentLogId);
detail.setMedicationId(med.getId());
detail.setTimeGiven(txtTime.getText().trim());
detail.setWasTaken(cmbWasTaken.getSelectedItem().toString().equals("Yes"));
detail.setSideEffects(txtSideEffects.getText().trim());

boolean saved = dao.insert(detail);
if (saved) {
    tml_dao.InputValidator.showSuccess(this, "Medication added to log.");
    clearForm();
    loadDetails();
} else {
    tml_dao.InputValidator.showError(this, "Failed to add medication.");
}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    int row = jTable1.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        return;
    }
    int id = (int) jTable1.getValueAt(row, 0);
    String medName = (String) jTable1.getValueAt(row, 1);
    if (tml_dao.InputValidator.confirmDelete(this, medName)) {
        tml_dao.LogDetailDAO dao = new tml_dao.LogDetailDAO();
        boolean deleted = dao.delete(id);
        if (deleted) {
            tml_dao.InputValidator.showSuccess(this, medName + " removed from log.");
            loadDetails();
        } else {
            tml_dao.InputValidator.showError(this, "Failed to delete.");
        }
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
   
this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cmbMedication;
    private javax.swing.JComboBox<String> cmbWasTaken;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLogInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel medication;
    private javax.swing.JScrollPane tblDetails;
    private javax.swing.JTextField txtSideEffects;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}

