/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trackmylove;

/**
 *
 * @author Lance
 */
public class LogFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogFrame.class.getName());

    /**
     * Creates new form LogFrame
     */
    private tml_model.Member loggedMember;

    public LogFrame(tml_model.Member member) {
        this.loggedMember = member;
        initComponents();
        setLocationRelativeTo(null);
        loadDropdowns();
        txtDate.setText(java.time.LocalDate.now().toString());
    }

    private void loadDropdowns() {
        tml_dao.MemberDAO dao = new tml_dao.MemberDAO();

        java.util.List<tml_model.Member> patients = dao.findPatients(loggedMember.getHouseholdId());
        cmbPatient.removeAllItems();
        for (tml_model.Member m : patients) {
            cmbPatient.addItem(m.getFullName() + " [" + m.getRole() + "] id:" + m.getId());
        }

        java.util.List<tml_model.Member> caregivers = dao.findCaregivers(loggedMember.getHouseholdId());
        cmbGivenBy.removeAllItems();
        for (tml_model.Member m : caregivers) {
            cmbGivenBy.addItem(m.getFullName() + " [" + m.getRole() + "] id:" + m.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbPatient = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbGivenBy = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblTitle.setText("Give Medication");

        jLabel1.setText("Patient");

        jLabel2.setText("Given By ");

        jLabel3.setText("Date * (YYYY-MM-DD)");

        txtDate.addActionListener(this::txtDateActionPerformed);

        jLabel4.setText("Notes");

        btnSave.setBackground(new java.awt.Color(29, 158, 117));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Log");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setText("Back to Dashboard");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGivenBy, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNotes))
                    .addComponent(btnSave)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDate))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbGivenBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // btnSave
        if (cmbPatient.getSelectedItem() == null) {
            tml_dao.InputValidator.showError(this, "Please select a patient.");
            return;
        }
        if (cmbGivenBy.getSelectedItem() == null) {
            tml_dao.InputValidator.showError(this, "Please select who is giving the medicine.");
            return;
        }
        if (!tml_dao.InputValidator.isValidDate(txtDate.getText().trim())) {
            tml_dao.InputValidator.showError(this, "Date must be in YYYY-MM-DD format.");
            return;
        }

        String patientStr = cmbPatient.getSelectedItem().toString();
        int patientId = Integer.parseInt(patientStr.split("id:")[1]);

        String giverStr = cmbGivenBy.getSelectedItem().toString();
        int giverId = Integer.parseInt(giverStr.split("id:")[1]);

        tml_model.MedicationLog log = new tml_model.MedicationLog();
        log.setPatientId(patientId);
        log.setGivenById(giverId);
        log.setLogDate(txtDate.getText().trim());
        log.setNotes(txtNotes.getText().trim());

        tml_dao.MedicationLogDAO logDAO = new tml_dao.MedicationLogDAO();
        int newLogId = logDAO.insert(log);

        if (newLogId == -1) {
            tml_dao.InputValidator.showError(this, "Failed to save log. Please try again.");
            return;
        }

        tml_dao.InputValidator.showSuccess(this, "Log saved! Now add the medications.");
        this.dispose();
        new trackmylove.LogDetailsFrame(loggedMember, newLogId).setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // btnBack
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbGivenBy;
    private javax.swing.JComboBox<String> cmbPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtNotes;
    // End of variables declaration//GEN-END:variables
}
